### ISSUE TITLE
Bower ownership transfer

### ISSUE THREAD

**Issue by Anthropic** [nick121212/schemaform-material#2]
Hi @nick121212 I've tried to email you, I was wanting to start doing releases to Bower soon and found you had used my repo name instead of making one that matches your repo after cloning my repo, I was wondering if you could transfer ownership of that project name in Bower back to me so I can start doing releases soon please?

**Comment by nick121212** [comment]
OK

**Comment by Anthropic** [comment]
@nick121212 thank you!
